// <auto-generated />
using System;
using Duurzame_Consumentkeuzes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duurzame_Consumentkeuzes.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231106125039_WasmachineSeeding3")]
    partial class WasmachineSeeding3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerDevice", b =>
                {
                    b.Property<string>("CustomersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DevicesId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "DevicesId");

                    b.HasIndex("DevicesId");

                    b.ToTable("CustomerDevice");
                });

            modelBuilder.Entity("CustomerEnergyLabel", b =>
                {
                    b.Property<string>("CustomersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EnergyLabelsId")
                        .HasColumnType("int");

                    b.HasKey("CustomersId", "EnergyLabelsId");

                    b.HasIndex("EnergyLabelsId");

                    b.ToTable("CustomerEnergyLabel");
                });

            modelBuilder.Entity("Duurzame_Consumentkeuzes.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "372725a0-0897-4dd1-a77a-0f9cce9ca7ad",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f75952f9-297e-40e3-97c1-27a937da38ed",
                            Email = "admin@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED2RQggumK9fWHiGjYYl/uVKtmeuBKmHP+e20W5LIr959r3t/5YGxysoPrFjegFflA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4acf121-613c-4949-9ecf-94c300b97ab5",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "db0f2ef1-0a19-4dc8-955e-c7069a7855ed",
                            AccessFailedCount = 0,
                            Budget = 450m,
                            ConcurrencyStamp = "b43e8e95-26d3-4a95-8f2f-2d536b68a562",
                            Email = "bruce@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "BRUCE@EXAMPLE.COM",
                            NormalizedUserName = "BRUCE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmRXBgCJjDk1/BiveF40X3LsCXrtc79pmF/RubgZhFREBkaFietwAhg6lldL7ySng==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b5e34192-4066-4e47-8409-567637d8b545",
                            TwoFactorEnabled = false,
                            UserName = "bruce@example.com"
                        },
                        new
                        {
                            Id = "d1ee95f0-a8bf-4d2b-a371-1cb9dbf84a0b",
                            AccessFailedCount = 0,
                            Budget = 500m,
                            ConcurrencyStamp = "4bdc4943-1475-4ac7-be7f-cb02581ded67",
                            Email = "gijs@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GIJS@EXAMPLE.COM",
                            NormalizedUserName = "GIJS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENpEJ0QvCFzBVogYFFwCzqFJhlzECKjDTlvlfdWO1gUv8DYa0r8yrRlrVqAKOPUpcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ff78077-6ef1-4dde-8e65-edc6df02e58d",
                            TwoFactorEnabled = false,
                            UserName = "gijs@example.com"
                        },
                        new
                        {
                            Id = "ca52d617-4bcd-4429-897a-89f43786d0d3",
                            AccessFailedCount = 0,
                            Budget = 650m,
                            ConcurrencyStamp = "de432db3-74de-450e-b933-62d3e5d96638",
                            Email = "rick@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RICK@EXAMPLE.COM",
                            NormalizedUserName = "RICK@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAQjPxRi3sTk2M62ssrgnlHCdxPdV5ovyOrjZ3C8YX/agd9HSYbSgSyDy4kdeoEy/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a13164b9-88ac-42ae-9c2f-c7db464b2abf",
                            TwoFactorEnabled = false,
                            UserName = "rick@example.com"
                        });
                });

            modelBuilder.Entity("Duurzame_Consumentkeuzes.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BuildDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnergyLabelId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnergyLabelId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Haier",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/haier-hw90-b14959u1.png",
                            Name = "Haier HW90 B14959U1",
                            Price = 599m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/samsung-ww90t534aaw.png",
                            Name = "Samsung WW90T534AAW",
                            Price = 649m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Bosch",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/bosch-serie-4-wgg04409nl.png",
                            Name = "Bosch Serie | 4 WGG04409NL",
                            Price = 699m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "AEG",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/aeg-lr6berlin.png",
                            Name = "AEG LR6BERLIN",
                            Price = 649m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Siemens",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/siemens-iq700-wg56b2a5nl.png",
                            Name = "Siemens IQ700 WG56B2A5NL",
                            Price = 1099m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Bosch",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/bosch-serie-6-wau28p95nl.png",
                            Name = "Bosch Serie | 6 WAU28P95NL",
                            Price = 875m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Siemens",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/siemens-iq300-wm14n297nl.png",
                            Name = "Siemens IQ300 WM14N297NL",
                            Price = 779m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Beko",
                            EnergyLabelId = 3,
                            ImagePath = "/images/devices/wasmachines/beko-wtv8712blw1.png",
                            Name = "Beko WTV8712BLW1",
                            Price = 399m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Whirlpool",
                            EnergyLabelId = 2,
                            ImagePath = "/images/devices/wasmachines/whirlpool-ffb-9458-wv-be.png",
                            Name = "Whirlpool FFB 9458 WV BE",
                            Price = 403m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Beko",
                            EnergyLabelId = 3,
                            ImagePath = "/images/devices/wasmachines/beko-wtv8711bc1.png",
                            Name = "Beko WTV8711BC1",
                            Price = 429m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Bosch",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/bosch-serie-6-kgn39aiat.png",
                            Name = "Bosch Serie | 6 KGN39AIAT",
                            Price = 1249m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Siemens",
                            EnergyLabelId = 2,
                            ImagePath = "/images/devices/koelkasten/siemens-kg39e8xba.png",
                            Name = "Siemens KG39E8XBA",
                            Price = 839m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "LG",
                            EnergyLabelId = 2,
                            ImagePath = "/images/devices/koelkasten/lg-gbp62pznbc.png",
                            Name = "LG GBP62PZNBC",
                            Price = 1009m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "LG",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/lg-gbb92stbap.png",
                            Name = "LG GBB92STBAP",
                            Price = 1378m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Siemens",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/siemens-iq500-kg39naiat.png",
                            Name = "Siemens IQ500 KG39NAIAT",
                            Price = 1399m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Etna",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/etna-kks4088.png",
                            Name = "Etna KKS4088",
                            Price = 348m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Siemens",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/siemens-ku15raff0.png",
                            Name = "Siemens KU15RAFF0",
                            Price = 576m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Siemens",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/siemens-ki51fade0.png",
                            Name = "Siemens KI51FADE0",
                            Price = 893.36m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Etna",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/etna-kkd4122.png",
                            Name = "Etna KKD4122 ",
                            Price = 499m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Bosch",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/koelkasten/bosch-ksv33vlep.png",
                            Name = "Bosch KSV33VLEP",
                            Price = 719m,
                            Type = "Koelkast"
                        },
                        new
                        {
                            Id = 21,
                            Brand = "AEG",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/aeg-lwr7796ud6.png",
                            Name = "AEG LWR7796UD6",
                            Price = 1249m,
                            Type = "Wasmachine"
                        },
                        new
                        {
                            Id = 22,
                            Brand = "Samsung",
                            EnergyLabelId = 1,
                            ImagePath = "/images/devices/wasmachines/samsung-bespoke-autodose-5000-serie-ww11bb534aabs2.png",
                            Name = "Samsung Bespoke Autodose 5000 serie WW11BB534AABS2",
                            Price = 749m,
                            Type = "Wasmachine"
                        });
                });

            modelBuilder.Entity("Duurzame_Consumentkeuzes.Models.EnergyLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EfficiencyClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnergyLabels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfficiencyClass = "A",
                            ImagePath = "/images/energylabels/energylabela.png"
                        },
                        new
                        {
                            Id = 2,
                            EfficiencyClass = "B",
                            ImagePath = "/images/energylabels/energylabelb.png"
                        },
                        new
                        {
                            Id = 3,
                            EfficiencyClass = "C",
                            ImagePath = "/images/energylabels/energylabelc.png"
                        },
                        new
                        {
                            Id = 4,
                            EfficiencyClass = "D",
                            ImagePath = "/images/energylabels/energylabeld.png"
                        },
                        new
                        {
                            Id = 5,
                            EfficiencyClass = "E",
                            ImagePath = "/images/energylabels/energylabele.png"
                        },
                        new
                        {
                            Id = 6,
                            EfficiencyClass = "F",
                            ImagePath = "/images/energylabels/energylabelf.png"
                        },
                        new
                        {
                            Id = 7,
                            EfficiencyClass = "G",
                            ImagePath = "/images/energylabels/energylabelg.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e0f4adb4-8c3d-45ff-a814-62c3c873fba5",
                            Name = "Administrators",
                            NormalizedName = "ADMINISTRATORS"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "372725a0-0897-4dd1-a77a-0f9cce9ca7ad",
                            RoleId = "e0f4adb4-8c3d-45ff-a814-62c3c873fba5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CustomerDevice", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duurzame_Consumentkeuzes.Models.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerEnergyLabel", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duurzame_Consumentkeuzes.Models.EnergyLabel", null)
                        .WithMany()
                        .HasForeignKey("EnergyLabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duurzame_Consumentkeuzes.Models.Device", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.EnergyLabel", "EnergyLabel")
                        .WithMany("Devices")
                        .HasForeignKey("EnergyLabelId");

                    b.Navigation("EnergyLabel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Duurzame_Consumentkeuzes.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Duurzame_Consumentkeuzes.Models.EnergyLabel", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
